/**
 * .agentrules / .cursorrules template generator.
 * Forces AI agents to read the Constitution file before any task.
 *
 * Supports two setup modes:
 * - global: Master Architect workspace
 * - module: Module Owner workspace (scoped context)
 */

/**
 * Generate agent rules content.
 * @param {string} prefix       - Project prefix (e.g. "LC247", "MYAPP")
 * @param {string} target       - Agent target: "antigravity" | "cursor" | "both"
 * @param {'global'|'module'} setupMode - Setup mode
 * @param {string} [moduleName] - Module name (for module mode), e.g. "Payment"
 * @returns {string} Full agent rules file content
 */
export function getAgentRules(prefix, target, setupMode = 'global', moduleName = '') {
    const agentName = {
        antigravity: 'Antigravity (Gemini)',
        cursor: 'Cursor',
        both: 'Antigravity | Cursor',
    }[target] || 'Antigravity | Cursor';

    const isModule = setupMode === 'module';
    const moduleTag = isModule ? `Module-${moduleName}` : '';

    const roleDesc = isModule
        ? `You are ${agentName}, an autonomous AI agent operating within the ${prefix} project ecosystem, scoped to **[${moduleTag}]**.`
        : `You are ${agentName}, an autonomous AI agent operating as the **Master Architect** of the ${prefix} project ecosystem.`;

    const contextIsolation = isModule
        ? getModuleIsolation(moduleTag)
        : getGlobalIsolation();

    return `# ═══════════════════════════════════════════════════════════════════════════════
# Agent Rules — Auto-generated by init-antigravity-workflow
# Project Prefix: ${prefix}
# Setup Mode: ${setupMode}${isModule ? `\n# Module: ${moduleName}` : ''}
# ═══════════════════════════════════════════════════════════════════════════════

${roleDesc}

## ⚠️ MANDATORY PRE-FLIGHT CHECK (BEFORE ANY TASK)

Before executing ANY user request, you MUST:

1. **Read the Constitution file:**
   \`.antigravity/00_${prefix}_Agent_Workflow.md\`

2. **Read the Context Router:**
   \`.antigravity/00_Core_Routing.md\`

3. **If resuming a session:** Read \`execution_status\` from the Jira ticket description
   to determine current progress. NEVER restart from Round 0 if progress exists.

4. **Follow the 4-Round Interactive Wizard** defined in the Constitution.
   DO NOT write any code until all prerequisite rounds are approved.

## Context Isolation Rules

${contextIsolation}

## Lego Architecture

When you need to understand the architecture, compose a view by joining:
1. \`[Global-Convention] Master_Architecture.md\` — system-wide blueprint
2. ${isModule ? `\`[${moduleTag}] Architecture_Map.md\` — your module's local blueprint` : 'All `[Module-*] Architecture_Map.md` files — each module\'s local blueprint'}

## MCP Integration

This project uses the following Model Context Protocol servers:
- **Jira MCP**: Task management, ticket CRUD, status tracking.
- **Confluence MCP**: PRD retrieval, documentation search.
- **NotebookLM MCP**: Convention files, ADRs, troubleshooting guides, knowledge base.

## State Commands

The agent responds to these slash commands:
- \`/pause\`    — Save current state to Jira Manifest and halt.
- \`/resume\`   — Restore state from Jira Manifest and continue.
- \`/handover\` — Prepare a transfer package for another developer.
`;
}

// ─── Context Isolation Helpers ───────────────────────────────────────────────

function getGlobalIsolation() {
    return `As **Master Architect**, you have full visibility across the knowledge base:

- ✅ **[Global-Convention]** — Coding standards, architecture rules (READ/WRITE)
- ✅ **[Global-ADR]** — System-wide Architecture Decision Records (READ/WRITE)
- ✅ **[Global-Troubleshooting]** — System-wide post-mortems (READ/WRITE)
- ✅ **[Module-*]** — All module-specific files (READ for oversight)`;
}

function getModuleIsolation(moduleTag) {
    return `You are operating under **Context Isolation**. Strict scoping rules apply:

### ✅ Allowed
- **[Global-Convention]** — System-wide coding standards (READ)
- **[Global-ADR]** — System-wide architecture decisions (READ)
- **[Global-Troubleshooting]** — System-wide post-mortems (READ)
- **[${moduleTag}]** — Your module's files (READ/WRITE)

### ❌ Forbidden
- **[Module-*]** (other modules) — NEVER read other module files.
  → Risk: Context overload, hallucination, cross-contamination.
  → Action: Escalate to the Master Architect if cross-module knowledge is needed.`;
}

/**
 * Returns the appropriate filename for the agent rules file.
 * @param {string} target - Agent target: "antigravity" | "cursor" | "both"
 * @returns {string} Filename
 */
export function getAgentRulesFilename(target) {
    switch (target) {
        case 'cursor':
            return '.cursorrules';
        case 'antigravity':
            return '.agentrules';
        case 'both':
        default:
            return '.agentrules';
    }
}
