/**
 * .agentrules / .cursorrules template generator.
 * Forces AI agents to read the Constitution file before any task.
 */

/**
 * Generate agent rules content.
 * @param {string} prefix   - Project prefix (e.g. "LC247", "BTRACK")
 * @param {string} target   - Agent target: "antigravity" | "cursor" | "both"
 * @returns {string} Full agent rules file content
 */
export function getAgentRules(prefix, target) {
    const agentName = {
        antigravity: 'Antigravity (Gemini)',
        cursor: 'Cursor',
        both: 'Antigravity | Cursor',
    }[target] || 'Antigravity | Cursor';

    return `# ═══════════════════════════════════════════════════════════════════════════════
# Agent Rules — Auto-generated by init-antigravity-workflow
# Project Prefix: ${prefix}
# ═══════════════════════════════════════════════════════════════════════════════

You are ${agentName}, an autonomous AI agent operating within the ${prefix} project ecosystem.

## ⚠️ MANDATORY PRE-FLIGHT CHECK (BEFORE ANY TASK)

Before executing ANY user request, you MUST:

1. **Read the Constitution file:**
   \`.antigravity/00_${prefix}_Agent_Workflow.md\`

2. **If resuming a session:** Read \`execution_status\` from the Jira ticket description
   to determine current progress. NEVER restart from Round 0 if progress exists.

3. **Follow the 4-Round Interactive Wizard** defined in the Constitution.
   DO NOT write any code until all prerequisite rounds are approved.

## Context Categorization Rules

When retrieving context from NotebookLM, prioritize files by these prefixes:
- **[Convention]**: Coding standards, folder structures, state management patterns.
- **[ADR]**: Architecture Decision Records — past decisions on libraries, logic flows.
- **[Troubleshooting]**: Post-mortems, bug logs, required fixes.
- **[Feature-Logic]**: Complex business rules (payment calculations, role permissions).

## MCP Integration

This project uses the following Model Context Protocol servers:
- **Jira MCP**: Task management, ticket CRUD, status tracking.
- **Confluence MCP**: PRD retrieval, documentation search.
- **NotebookLM MCP**: Convention files, ADRs, troubleshooting guides, knowledge base.

## State Commands

The agent responds to these slash commands:
- \`/pause\`    — Save current state to Jira Manifest and halt.
- \`/resume\`   — Restore state from Jira Manifest and continue.
- \`/handover\` — Prepare a transfer package for another developer.
`;
}

/**
 * Returns the appropriate filename for the agent rules file.
 * @param {string} target - Agent target: "antigravity" | "cursor" | "both"
 * @returns {string} Filename
 */
export function getAgentRulesFilename(target) {
    switch (target) {
        case 'cursor':
            return '.cursorrules';
        case 'antigravity':
            return '.agentrules';
        case 'both':
        default:
            return '.agentrules';
    }
}
